### ISSUE TITLE
Estimate remove api-v2 from rain report

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1116]
THIS TICKET IS ACTUALLY PART OF RAIN REPORT NOT LIZARD CLIENT,
DUPLICATE OF https://github.com/nens/rain_report/issues/27
BUT I COULDNOT LINK IT TO THE BOARD

Ha Tom, Lizard gaat API v2 deprecated. Ik heb hiervoor 2 javascript clients gevonden die er nog gebruik van maken: https://github.com/nens/rain_report/issues/27 en https://github.com/nens/kpi-dashboard/issues/54 . De eerste moet vrijwel zeker opgepakt worden, de tweede misschien niet (hangt van B&O contract af). Zou jij misschien een korte inschatting kunnen maken van deze tickets? Dit ivm plannen van het moment wanneer we de API v2 uit gaan zetten.

**Comment by Derryrover** [comment]
@GeOdin 

Hi Madeleine could you have a look at this?

**Comment by GeOdin** [comment]
Note from Lex:
It might be a good idea to see if we can go from api v2 to api v4 directly.
Api v4 is already stable, and in that case we wouldn't have to update this when api v3 becomes deprecated.

**Comment by GeOdin** [comment]
There were some troubles with starting up the rain_report repo.
Downgrading node to v8.17.0 with nvm (same version as currently used for lizard-client) solved this problem.
I updated the readme:
https://github.com/nens/rain_report/commit/da3f21004abb10501211deb8438cf93ec8be3019

Even with adding the password for authorization in the webpack-dev-server.js, you still get a redirect to demo.lizard.net.
I will try to see if I can get past this redirect on Monday. (localize and temporarly shutting it down)

Further to do:
* it may be necessary to test on staging because it may not be possible to test on dev
* STAGING -> **download and save config file from server!!!!!** before you get started with staging (see readme)
* PRODUCTION -> together with Tom
  - also **download and save config file from server!!!!!** before you get started with staging (see readme)

**Comment by caspervdw** [comment]
@GeOdin @lexvand 

> Note from Lex:
It might be a good idea to see if we can go from api v2 to api v4 directly.
Api v4 is already stable, and in that case we wouldn't have to update this when api v3 becomes deprecated.

This crossed my mind as well, but I think we should first make the API v4 stable. Otherwise we will become locked in on the API v4. 
In other words: you can use API v4, but there are no guarantees it will remain working as it does right now.

**Comment by GeOdin** [comment]
@caspervdw 
Thank you for the input. :)

**Comment by Derryrover** [comment]
@GeOdin 

Deployed 1.6.32 to staging.

Todo:
- review 1.6.32 (Tom)
- Testing: is staging suitable for testing and what other actions do we need to take? Or should we deploy to production and rollback if someone complaints? (Madeleine and Tom)
- deploy to prod

**Comment by Derryrover** [comment]
When something goes wrong:

Revert prod back to v1.6.29
I verified that the config.json was not changed in the meanwhile.

**Comment by Derryrover** [comment]
closed as duplicate of https://github.com/nens/rain_report/issues/27
