### ISSUE TITLE
Only show observationtype_parameter in graph view instead of location_name + observationtype_paramater

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-client#1135]
We currently show the available observationtype_paramaters in the portal like below (location_name+oberservationtype_parameter). The point is that the parameters become unreadable and that the location name is visualized over and over again whilst it is already visualized in the dark grey header. I would like to remove the location_name in the list of parameters and only show the observationtype_parameter:   

![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/60ce7a85-0fd0-4dc4-a0a8-7c75872afa41)

**Comment by lexvand** [comment]
This is breaking stuff for a lot of assets that have different child locations, e.g. Helsdeur with buitenwaterstand and binnenwaterstand and different debieten.

**Comment by Derryrover** [comment]
@joeriverheijden 
@lexvand 

We for example also see it happen here that text is cut off:
https://demo.lizard.net/nl/charts/topography,assetgroup$9c2d7b6/multi-point/measuringstation$223364+measuringstation$221840/@52.5046,5.6964,12/-2Days0Hours+0Days3Hours

Here it is a pitty because not even the complete vertical space of the sidebar is used.
In my opinion the text should just wrap to the newline. This would solve both your problems.

Normally making text wrap to a newline would be a very small change, but here javascript (instead of simple css) is used to cut of the text. Also absolute positioning is used to wrap the box around the text. This makes everything ten times more complicated.

**Comment by lexvand** [comment]
It would be nice if we can build some simple logic to recognize when all location names start with the same string and cut that part off. But I think we should leave this for the new client.
