### ISSUE TITLE
No graph shown for region selection on temporal raster with aggregation_type=average

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-client#1196]
This issue is reported by Water Insight. Seen in (requires read rights for Water Insight): https://waterinsight.lizard.net/viewer/en/map/neutral,raster$a6cda48,raster$96b5a51/region/313537/@51.4764,4.1267,12/Sep,11,2020-Sep,26,2020

When selecting one of the parcels in region selection mode, a correct API call is done, [the response seems to be okay](https://waterinsight.lizard.net/api/v3/raster-aggregates/?agg=average&boundary_type=CUSTOM&geom_id=313537&rasters=96b5a51&srs=EPSG:4326&start=2020-09-11T07:44:35&stop=2020-09-26T07:56:00&window=86400000), but no graph is rendered in the omnibox.

I tracked it down to the following code snippet: https://github.com/nens/lizard-client/blob/master/app/components/omnibox/templates/geometry-cards.html#L157-L163

I see no console errors. Why doesn't this work? Is the data format correct for the graph? Why doesn't this work? If this can be fixed with a small adjustment (e.g. include `ng-if="properties.agg === 'average'"` in the list of graphs above this snippet), then it is worth to perform a fix.

**Comment by hoanphungt** [comment]
@Derryrover 
I fixed a bug with displaying graph for raster region selection. If you follow the link in the description (with user role in Water Insight) and then select a region, you will see that there is no graph in the omnibox. The bug happened because the ng-if statement is incorrect (raster should be a string). But apart from it, the original code also misses the x and y labels. The x labels are timestamps, so they also need to be converted to date time format. 

Could you review the connected PR?

Thanks,
Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
@lexvand 

Hi Hoan and Lex,

Thanks for finding fixing this bug! 
I think following your logic the code looks good.
I thus approved the code.

I didnot test it because I do not have roles for water insight. Would you prefer me to test it?
Then I can ask if I can have user-role for water insight.

Another concern may be regression tests. How can we know this 'change' will not introduce new bugs for other usecases?
I also do not have an answer there. Looking at the change it should not introduce new bugs, but I really do not have the confidence in this app.
We thus need to do extensive testing on staging.

kr Tom

**Comment by lexvand** [comment]
Test on staging: The fix does what was intended for aggregation types sum and average. I just found two issues:
- Aggregation type None results in all null values, so we should not draw a graph in that case. This can probably be fixed by adjusting the if-then-else statement. Ideally, we would show a warning like "Nothing can be shown because no aggregation type is set for this layer.", but let's not mess things up too much.
- When in region selection mode, with the Regen layer active in combination with a layer with aggregation type curve or counts, the Regen data is not being plotted. The Console shows some errors about determining the x, y, width and length of rectangles. With only the Regen layer active it works just fine. On production the combination does work. @hoanphungt Can you check what happens here? I could demonstrate it to you. If we can't find the reason for this behavior I still consider to go to production, as I consider the fix more valuable than the potential new bug.

**Comment by hoanphungt** [comment]
- Fixed aggregation type None by not showing the graph and displaying the text: "Nothing can be shown because no aggregation type is set for this layer" instead.
- Regen layer graph data not showing up in combination with other aggregation type (curve/counts): Hoan tested it and confirmed that this is already an issue before the fix. However, this bug does not happen on production so we leave it as it is.

Another staging release has been made to improve handling of aggregation type None.
